server:
  port: 8082
logging:
  file:
    name: D://logs/globle.log
  level:
    tg:
      bot:
        tw:
          mapper: debug


mybatis:
  type-aliases-package: tg.bot.tw.entity
  mapper-locations:  classpath:mapper/*.xml
