server:
  port: 8082
logging:
  file:
    name: D://logs/globle.log
  level:
    tg:
      bot:
        tw:
          mapper: debug
task:
  poxy:
    hostname: 119.28.55.50
    port: 10801
    userName: 98984
    passWord: 35133
  http:
    # newcall重试次数
    maxRetryCount: 3
    # 预期状态码
    expectedStatusCode: 0


mybatis:
  type-aliases-package: tg.bot.tw.entity
  mapper-locations:  classpath:mapper/*.xml
